# Generated by Django 5.2.7 on 2025-10-15 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fiscal_year_start',
            field=models.DateField(blank=True, help_text='Start of fiscal year (e.g., Jan 1)', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='industry_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Legal/registered name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='registration_number',
            field=models.CharField(blank=True, help_text='Business registration number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Company trading name', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, help_text='Tax/VAT identification number', max_length=100, null=True),
        ),
    ]
