# Generated by Django 5.2.7 on 2025-10-07 10:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_customer_taxrate_vendor_budget_expensecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedasset',
            name='acquisition_method',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('LEASE', 'Lease'), ('DONATION', 'Donation'), ('CONSTRUCTION', 'Construction'), ('CAPITALIZED_EXPENSE', 'Capitalized Expense'), ('OTHER', 'Other')], default='PURCHASE', help_text='How the asset was acquired', max_length=30),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode/RFID tag', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='category',
            field=models.CharField(choices=[('OFFICE_EQUIPMENT', 'Office Equipment'), ('FURNITURE', 'Furniture'), ('VEHICLES', 'Vehicles'), ('BUILDINGS', 'Buildings'), ('LAND', 'Land'), ('SOFTWARE', 'Software'), ('LEASEHOLD_IMPROVEMENTS', 'Leasehold Improvements'), ('MACHINERY', 'Machinery'), ('COMPUTER_EQUIPMENT', 'Computer Equipment'), ('OTHER', 'Other')], default='OTHER', help_text='Asset category', max_length=30),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='custodian',
            field=models.CharField(blank=True, help_text='Person responsible for the asset', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='custodian_employee_id',
            field=models.CharField(blank=True, help_text='Employee ID of custodian', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='department',
            field=models.CharField(blank=True, help_text='Department responsible for the asset', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_date',
            field=models.DateField(blank=True, help_text='Date the asset was disposed', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_method',
            field=models.CharField(blank=True, help_text='How the asset was disposed (sold, scrapped, etc.)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_notes',
            field=models.TextField(blank=True, help_text='Notes about the disposal', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='disposal_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Proceeds from disposal', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='funding_source',
            field=models.CharField(blank=True, help_text='Source of funding for the asset', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='grant_number',
            field=models.CharField(blank=True, help_text='Grant or funding reference number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='insurance_company',
            field=models.CharField(blank=True, help_text='Insurance company name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='insurance_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Insurance coverage amount', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='Insurance policy expiry date', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='insurance_policy_number',
            field=models.CharField(blank=True, help_text='Insurance policy number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual insurance premium', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_depreciated',
            field=models.BooleanField(default=True, help_text='Should this asset be depreciated'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_insured',
            field=models.BooleanField(default=False, help_text='Is this asset insured'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_leased',
            field=models.BooleanField(default=False, help_text='Is this asset leased'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='is_under_warranty',
            field=models.BooleanField(default=False, help_text='Is this asset under warranty'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='last_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of last maintenance', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='maintenance_cost_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual maintenance budget', max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='maintenance_provider',
            field=models.CharField(blank=True, help_text='Maintenance service provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='maintenance_schedule',
            field=models.CharField(blank=True, help_text="Maintenance schedule (e.g., 'Monthly', 'Quarterly')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='manufacturer',
            field=models.CharField(blank=True, help_text='Asset manufacturer', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='model',
            field=models.CharField(blank=True, help_text='Asset model', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='next_maintenance_date',
            field=models.DateField(blank=True, help_text='Date of next scheduled maintenance', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the asset', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='purchase_order_number',
            field=models.CharField(blank=True, help_text='Purchase order reference', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Manufacturer serial number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='tags',
            field=models.CharField(blank=True, help_text='Tags for categorization and search', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor/supplier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_assets', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='warranty_end_date',
            field=models.DateField(blank=True, help_text='Warranty end date', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='warranty_provider',
            field=models.CharField(blank=True, help_text='Warranty provider', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='warranty_start_date',
            field=models.DateField(blank=True, help_text='Warranty start date', null=True),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='warranty_terms',
            field=models.TextField(blank=True, help_text='Warranty terms and conditions', null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='account',
            field=models.ForeignKey(help_text='GL account for this asset', on_delete=django.db.models.deletion.PROTECT, related_name='fixed_assets', to='accounting.account'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='accumulated_depreciation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total depreciation charged to date', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='asset_code',
            field=models.CharField(db_index=True, help_text='Unique asset identification code', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='book_value',
            field=models.DecimalField(decimal_places=2, help_text='Current book value (cost - accumulated depreciation)', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='depreciation_method',
            field=models.CharField(choices=[('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('UNITS_OF_PRODUCTION', 'Units of Production')], default='STRAIGHT_LINE', help_text='Depreciation calculation method', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed asset description', null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the asset currently active/in use'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the asset', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='name',
            field=models.CharField(help_text='Asset name/description', max_length=255),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, help_text='Original purchase cost', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='purchase_date',
            field=models.DateField(help_text='Date the asset was acquired'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='salvage_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated salvage value at end of life', max_digits=15),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='useful_life_years',
            field=models.IntegerField(help_text='Expected useful life in years'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['asset_code', 'category'], name='accounting__asset_c_fb7034_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['is_active', 'category'], name='accounting__is_acti_d49011_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['purchase_date'], name='accounting__purchas_a0159f_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['department'], name='accounting__departm_4b2020_idx'),
        ),
        migrations.AddIndex(
            model_name='fixedasset',
            index=models.Index(fields=['custodian'], name='accounting__custodi_0d728c_idx'),
        ),
    ]
