# Generated by Django 5.2.7 on 2025-10-07 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_fixedasset_acquisition_method_fixedasset_barcode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_date', models.DateField(db_index=True)),
                ('statement_date', models.DateField()),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('adjusted_book_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.account')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_completed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(db_index=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('statement_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('CHECK', 'Check'), ('TRANSFER', 'Transfer'), ('FEE', 'Bank Fee'), ('INTEREST', 'Interest'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('check_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_date', models.DateField(blank=True, null=True)),
                ('asset_transaction_type', models.CharField(blank=True, help_text='Purchase, Maintenance, Disposal, etc.', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_statements', to='accounting.account')),
                ('fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='accounting.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_statements', to='accounting.journalentry')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('DEPOSIT_IN_TRANSIT', 'Deposit in Transit'), ('OUTSTANDING_CHECK', 'Outstanding Check'), ('BANK_ERROR', 'Bank Error'), ('BOOK_ERROR', 'Book Error'), ('INTEREST_EARNED', 'Interest Earned'), ('BANK_FEE', 'Bank Fee'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_addition', models.BooleanField(default=True, help_text='True if adding to book balance, False if subtracting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fixed_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_adjustments', to='accounting.fixedasset')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_adjustments', to='accounting.journalentry')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='accounting.bankreconciliation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['account', 'status'], name='accounting__account_61d69b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['reconciliation_date'], name='accounting__reconci_816cfa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together={('account', 'reconciliation_date')},
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['account', 'statement_date'], name='accounting__account_767e7c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['is_reconciled', 'statement_date'], name='accounting__is_reco_86aa8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['transaction_id'], name='accounting__transac_d5f3f2_idx'),
        ),
    ]
