# Generated by Django 5.2.7 on 2025-10-07 11:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_bankreconciliation_bankstatement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTaxInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_depreciation_method', models.CharField(choices=[('MACRS', 'MACRS (Modified Accelerated Cost Recovery System)'), ('STRAIGHT_LINE', 'Straight Line'), ('DECLINING_BALANCE', 'Declining Balance'), ('SECTION_179', 'Section 179 Deduction'), ('BONUS_DEPRECIATION', 'Bonus Depreciation')], default='MACRS', help_text='Depreciation method for tax purposes', max_length=30)),
                ('property_class', models.CharField(choices=[('CLASS_3', '3-year property'), ('CLASS_5', '5-year property'), ('CLASS_7', '7-year property'), ('CLASS_10', '10-year property'), ('CLASS_15', '15-year property'), ('CLASS_20', '20-year property'), ('CLASS_27_5', '27.5-year property'), ('CLASS_39', '39-year property'), ('NON_DEPRECIABLE', 'Non-depreciable')], default='CLASS_5', help_text='IRS property class for depreciation', max_length=20)),
                ('tax_useful_life_years', models.IntegerField(blank=True, help_text='Useful life for tax depreciation (may differ from book life)', null=True)),
                ('tax_basis', models.DecimalField(decimal_places=2, help_text='Tax basis for depreciation calculations', max_digits=15)),
                ('section_179_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Section 179 deduction taken', max_digits=15)),
                ('bonus_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bonus depreciation taken', max_digits=15)),
                ('tax_accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Accumulated depreciation for tax purposes', max_digits=15)),
                ('tax_book_value', models.DecimalField(decimal_places=2, help_text='Tax book value (basis - accumulated tax depreciation)', max_digits=15)),
                ('assessed_value', models.DecimalField(blank=True, decimal_places=2, help_text='Assessed value for property tax', max_digits=15, null=True)),
                ('property_tax_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Property tax rate (as decimal, e.g., 0.0125 for 1.25%)', max_digits=5, null=True)),
                ('property_tax_jurisdiction', models.CharField(blank=True, help_text='Property tax jurisdiction', max_length=100, null=True)),
                ('tax_lot_number', models.CharField(blank=True, help_text='Tax lot number for property records', max_length=50, null=True)),
                ('reported_on_form_4562', models.BooleanField(default=False, help_text='Has this asset been reported on Form 4562')),
                ('reported_on_form_4797', models.BooleanField(default=False, help_text='Has this asset been reported on Form 4797 (sales)')),
                ('tax_notes', models.TextField(blank=True, help_text='Tax-specific notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Asset Tax Information',
                'verbose_name_plural': 'Asset Tax Information',
            },
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='completed_by',
        ),
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reconciliationadjustment',
            name='reconciliation',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='account',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='fixed_asset',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='journal_entry',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='reconciled_by',
        ),
        migrations.RemoveField(
            model_name='reconciliationadjustment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='reconciliationadjustment',
            name='fixed_asset',
        ),
        migrations.RemoveField(
            model_name='reconciliationadjustment',
            name='journal_entry',
        ),
        migrations.AlterModelOptions(
            name='taxrate',
            options={'ordering': ['-effective_date', 'name']},
        ),
        migrations.AlterModelOptions(
            name='taxreturn',
            options={'ordering': ['-tax_period_end', '-return_number']},
        ),
        migrations.AddField(
            model_name='taxrate',
            name='effective_date',
            field=models.DateField(default='2024-01-01', help_text='Date when this tax rate becomes effective'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='end_date',
            field=models.DateField(blank=True, help_text='Date when this tax rate expires', null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='jurisdiction',
            field=models.CharField(blank=True, help_text='Tax jurisdiction (state, local, federal)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='tax_type',
            field=models.CharField(choices=[('INCOME', 'Income Tax'), ('SALES', 'Sales Tax'), ('PROPERTY', 'Property Tax'), ('DEPRECIATION', 'Depreciation Tax'), ('OTHER', 'Other')], default='INCOME', max_length=20),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='balance_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='deductions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='filed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_returns_filed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='gross_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='jurisdiction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='return_type',
            field=models.CharField(choices=[('FORM_1040', 'Form 1040 (Individual)'), ('FORM_1120', 'Form 1120 (Corporation)'), ('FORM_1120S', 'Form 1120S (S-Corp)'), ('FORM_1065', 'Form 1065 (Partnership)'), ('FORM_4562', 'Form 4562 (Depreciation)'), ('FORM_4797', 'Form 4797 (Sales of Assets)'), ('PROPERTY_TAX', 'Property Tax Return'), ('OTHER', 'Other')], default='FORM_1120', max_length=20),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='taxable_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='taxrate',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Tax rate as percentage', max_digits=5),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='return_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FILED', 'Filed'), ('PAID', 'Paid'), ('AMENDED', 'Amended'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='tax_period_end',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='tax_period_start',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='total_tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['tax_type', 'jurisdiction', 'effective_date'], name='accounting__tax_typ_1e9023_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['return_type', 'tax_period_end'], name='accounting__return__0b447f_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['status', 'due_date'], name='accounting__status_f54c6e_idx'),
        ),
        migrations.AddField(
            model_name='assettaxinfo',
            name='asset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_info', to='accounting.fixedasset'),
        ),
        migrations.DeleteModel(
            name='BankReconciliation',
        ),
        migrations.DeleteModel(
            name='BankStatement',
        ),
        migrations.DeleteModel(
            name='ReconciliationAdjustment',
        ),
    ]
