# Generated by Django 5.2.7 on 2025-10-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_aimodel_anomalydetectionmodel_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinsight',
            name='impact_score',
            field=models.DecimalField(decimal_places=2, help_text='Potential impact score (0-100)', max_digits=15),
        ),
    ]
