# Generated by Django 5.2.7 on 2025-10-08 08:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_fix_decimal_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='accuracy_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='f1_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='precision_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='recall_score',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='anomalydetectionmodel',
            name='sensitivity_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.80'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='anomalydetectionmodel',
            name='specificity_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.85'), max_digits=6),
        ),
    ]
