# Generated by Django 5.2.7 on 2025-10-08 11:15

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_notification_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardKPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('metric_type', models.CharField(choices=[('CURRENCY', 'Currency'), ('PERCENTAGE', 'Percentage'), ('NUMBER', 'Number'), ('RATIO', 'Ratio')], default='CURRENCY', max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('previous_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('trend_direction', models.CharField(choices=[('UP', 'Increasing'), ('DOWN', 'Decreasing'), ('STABLE', 'Stable')], default='STABLE', max_length=10)),
                ('trend_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('auto_update', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dashboard KPI Metric',
                'verbose_name_plural': 'Dashboard KPI Metrics',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('INVOICE_CREATED', 'Invoice Created'), ('INVOICE_PAID', 'Invoice Paid'), ('BILL_CREATED', 'Bill Created'), ('BILL_PAID', 'Bill Paid'), ('PAYMENT_RECEIVED', 'Payment Received'), ('PAYMENT_MADE', 'Payment Made'), ('JOURNAL_POSTED', 'Journal Entry Posted'), ('EXPENSE_APPROVED', 'Expense Approved'), ('ASSET_ADDED', 'Asset Added'), ('BUDGET_CREATED', 'Budget Created'), ('TAX_RETURN_FILED', 'Tax Return Filed')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Activity',
                'verbose_name_plural': 'Dashboard Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('SUCCESS', 'Success')], default='INFO', max_length=10)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('related_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_dismiss', models.BooleanField(default=False)),
                ('dismiss_after_hours', models.PositiveIntegerField(default=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Alert',
                'verbose_name_plural': 'Dashboard Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layout_columns', models.PositiveIntegerField(default=4)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('visible_widgets', models.JSONField(default=list)),
                ('hidden_widgets', models.JSONField(default=list)),
                ('auto_refresh', models.BooleanField(default=True)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('email_alerts', models.BooleanField(default=True)),
                ('browser_notifications', models.BooleanField(default=True)),
                ('default_date_range', models.CharField(default='last_30_days', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Settings',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('widget_type', models.CharField(choices=[('KPI_CARD', 'KPI Card'), ('CHART', 'Chart'), ('TABLE', 'Data Table'), ('SUMMARY', 'Summary Card'), ('ALERT', 'Alert/Notification')], max_length=20)),
                ('chart_type', models.CharField(blank=True, choices=[('LINE', 'Line Chart'), ('BAR', 'Bar Chart'), ('PIE', 'Pie Chart'), ('AREA', 'Area Chart'), ('DONUT', 'Donut Chart')], max_length=10, null=True)),
                ('position_x', models.PositiveIntegerField(default=0)),
                ('position_y', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=1)),
                ('height', models.PositiveIntegerField(default=1)),
                ('data_source', models.CharField(blank=True, max_length=100, null=True)),
                ('data_filter', models.JSONField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('refresh_interval', models.PositiveIntegerField(default=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
                'ordering': ['position_y', 'position_x'],
            },
        ),
        migrations.CreateModel(
            name='DashboardChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('period', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_data', to='accounting.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Dashboard Chart Data',
                'verbose_name_plural': 'Dashboard Chart Data',
                'ordering': ['sort_order', 'date', 'label'],
                'unique_together': {('widget', 'label', 'date')},
            },
        ),
    ]
