# Generated by Django 5.2.7 on 2025-10-15 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_remove_account_accounting__code_9d9368_idx_and_more'),
        ('companies', '0002_alter_company_options_company_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('company', 'bill_number')},
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['company', 'bill_date', 'status'], name='accounting__company_704427_idx'),
        ),
    ]
