# Generated by Django 5.2.7 on 2025-10-15 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_add_company_to_bill'),
        ('companies', '0002_alter_company_options_company_city_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='aiinsight',
            name='accounting__insight_debb5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiinsight',
            name='accounting__is_acti_c78c28_idx',
        ),
        migrations.RemoveIndex(
            model_name='aiprediction',
            name='accounting__predict_77f9c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='anomalyalert',
            name='accounting__status_0e74cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='anomalyalert',
            name='accounting__anomaly_1fdce1_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankreconciliation',
            name='accounting__account_61d69b_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankreconciliation',
            name='accounting__reconci_816cfa_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankstatement',
            name='accounting__account_767e7c_idx',
        ),
        migrations.RemoveIndex(
            model_name='bankstatement',
            name='accounting__is_reco_86aa8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounting__user_id_df8da8_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounting__notific_ea5a96_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxrate',
            name='accounting__tax_typ_1e9023_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxreturn',
            name='accounting__return__0b447f_idx',
        ),
        migrations.RemoveIndex(
            model_name='taxreturn',
            name='accounting__status_f54c6e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='anomalydetectionmodel',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aiinsight',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='companies.company'),
        ),
        migrations.AddField(
            model_name='aiprediction',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_predictions', to='companies.company'),
        ),
        migrations.AddField(
            model_name='anomalyalert',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_alerts', to='companies.company'),
        ),
        migrations.AddField(
            model_name='anomalydetectionmodel',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_detection_models', to='companies.company'),
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliations', to='companies.company'),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='companies.company'),
        ),
        migrations.AddField(
            model_name='budget',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='companies.company'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expense',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='companies.company'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='companies.company'),
        ),
        migrations.AddField(
            model_name='fixedasset',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='companies.company'),
        ),
        migrations.AddField(
            model_name='notification',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company'),
        ),
        migrations.AddField(
            model_name='payment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='reconciliationadjustment',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_adjustments', to='companies.company'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_rates', to='companies.company'),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_returns', to='companies.company'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='companies.company'),
        ),
        migrations.AlterUniqueTogether(
            name='aiinsight',
            unique_together={('company', 'insight_id')},
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('company', 'model_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='aiprediction',
            unique_together={('company', 'prediction_id')},
        ),
        migrations.AlterUniqueTogether(
            name='anomalyalert',
            unique_together={('company', 'alert_id')},
        ),
        migrations.AlterUniqueTogether(
            name='anomalydetectionmodel',
            unique_together={('company', 'model_name', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='bankreconciliation',
            unique_together={('company', 'account', 'reconciliation_date')},
        ),
        migrations.AlterUniqueTogether(
            name='bankstatement',
            unique_together={('company', 'transaction_id')},
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('company', 'name', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='documentcategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='expense',
            unique_together={('company', 'expense_number')},
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('company', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together={('company', 'user', 'title', 'created_at')},
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('company', 'payment_number')},
        ),
        migrations.AlterUniqueTogether(
            name='taxrate',
            unique_together={('company', 'name', 'jurisdiction')},
        ),
        migrations.AlterUniqueTogether(
            name='taxreturn',
            unique_together={('company', 'return_number')},
        ),
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('company', 'vendor_code')},
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['company', 'insight_type', 'priority'], name='accounting__company_c925c7_idx'),
        ),
        migrations.AddIndex(
            model_name='aiinsight',
            index=models.Index(fields=['company', 'is_active', 'generated_at'], name='accounting__company_ca1471_idx'),
        ),
        migrations.AddIndex(
            model_name='aiprediction',
            index=models.Index(fields=['company', 'prediction_type', 'prediction_date'], name='accounting__company_a4839e_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['company', 'status', 'severity'], name='accounting__company_60be1a_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalyalert',
            index=models.Index(fields=['company', 'anomaly_type', 'detected_at'], name='accounting__company_fdf44a_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['company', 'account', 'status'], name='accounting__company_5ea28c_idx'),
        ),
        migrations.AddIndex(
            model_name='bankreconciliation',
            index=models.Index(fields=['company', 'reconciliation_date'], name='accounting__company_69cff7_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'account', 'statement_date'], name='accounting__company_577833_idx'),
        ),
        migrations.AddIndex(
            model_name='bankstatement',
            index=models.Index(fields=['company', 'is_reconciled', 'statement_date'], name='accounting__company_364ddb_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['company', 'fiscal_year', 'is_active'], name='accounting__company_313f1c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['company', 'expense_date', 'status'], name='accounting__company_bd605f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'user', 'is_read', 'created_at'], name='accounting__company_a2e048_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['company', 'notification_type', 'created_at'], name='accounting__company_ecddce_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['company', 'payment_date'], name='accounting__company_7ed91e_idx'),
        ),
        migrations.AddIndex(
            model_name='taxrate',
            index=models.Index(fields=['company', 'tax_type', 'jurisdiction', 'effective_date'], name='accounting__company_95d3e3_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['company', 'return_type', 'tax_period_end'], name='accounting__company_47e870_idx'),
        ),
        migrations.AddIndex(
            model_name='taxreturn',
            index=models.Index(fields=['company', 'status', 'due_date'], name='accounting__company_95bbaf_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company', 'vendor_code'], name='accounting__company_654c36_idx'),
        ),
    ]
